#!/bin/bash

#sv start socklog-unix || exit 1

source /etc/envvars

sed -i \
    -e "s|{{DB_HOST}}|$DB_HOST|" \
    -e "s|{{DB_PORT}}|$DB_PORT|" \
    -e "s|{{DB_NAME}}|$DB_NAME|" \
    -e "s|{{DB_USER}}|$DB_USER|" \
    -e "s|{{DB_PASS}}|$DB_PASS|" \
    /var/www/html/app/config/local.php

exec 2>&1
exec nginx -g "daemon off;"
