#!/bin/bash

sv start php || exit 1

source /etc/envvars

cd /var/www/html/app
mkdir -p local/cache/prod local/config local/themes local/idp local/media/files local/media/images local/plugins
find /var/www/html/app/local/plugins -maxdepth 1 -mindepth 1 -type d -print0 | xargs --no-run-if-empty -0 ln -s -t /var/www/html/plugins
chown -R www-data:www-data /var/www/html

mkdir -p /var/log/mautic
chown -R www-data:www-data /var/log/mautic

mkdir -p /var/log/nginx

/var/www/html/app/console cache:clear
/var/www/html/app/console cache:warm
/var/www/html/app/console doctrine:migration:migrate --no-interaction

exec 2>&1
exec nginx -g "daemon off;"
