#!/bin/bash

#sv start socklog-unix || exit 1

source /etc/envvars

cd /var/www/html/app
mkdir -p cache/prod local/config local/themes local/idp local/media/files local/media/images
chown -R www-data:www-data /var/www/html

exec 2>&1
exec nginx -g "daemon off;"
